### ISSUE TITLE
AVAssetExportSession not play

### ISSUE THREAD

**Issue by JqyModi** [damikdk/LottieExportDemo#1]
Video of AVAssetExportSession export  not play

**Comment by damikdk** [comment]
Thanks for update. 

I just checked, it really doesn't work for new versions (3.1.5+) of Lottie anymore. But if you just clone this repo and just run **without** ``pod update``, it works! Works wrong, as expected.

I will implement ``AVAssetExportSession`` for new version later.

**Comment by damikdk** [comment]
Actually, it works for ``3.1.5`` too! You still just need to remove this [line](https://github.com/airbnb/lottie-ios/blob/9d37b62452ae6e5f5f0d1c2857a60cc0fb62f966/lottie-swift/src/Public/Animation/AnimationView.swift#L910) and clean build folder. Good luck
