### ISSUE TITLE
slow lottie animation video rendering with AVAssetWriter on iphone X and iphone XS

### ISSUE THREAD

**Issue by dragoncnv** [damikdk/LottieExportDemo#2]
Hi Damikdk,
I'm using your sample to render lottie animation to video with oldExport() method.
It works great on iphone 6s (export 5s video around 22 seconds). But on a iPhone X or Xs its takes to 4 minutes to export same video with same resolution settings. Is there any way to optimize this work better on iphone X, or Xs.. (newer devices)? 

Best regards,
DragonCNV

**Comment by damikdk** [comment]
@dragoncnv Hi. Sorry, we dropped this idea at all. Lottie is not ready for any export. For now

**Comment by orkenstein** [comment]
@damikdk so how do you render Lottie video now?

**Comment by damikdk** [comment]
@orkenstein Can't say cause of NDA, sorry.

**Comment by orkenstein** [comment]
@damikdk ok :D so, could you please point the direction at least?

**Comment by damikdk** [comment]
@orkenstein Try to use something else. Maybe not even ``Lottie``

Creator of [LottieInVideo](https://github.com/lvpengwei/LottieInVideo) recommend some [pag.io](https://pag.io/), for example. I don't know what is this, but there are some analogues of ``Lottie`` and ``lottie-ios``
